/* Generated By:JavaCC: Do not edit this line. MiniLangParserTreeConstants.java Version 4.1d1 */
public interface MiniLangParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTVARDECL = 2;
  public int JJTPRINTSTMT = 3;
  public int JJTIFSTMT = 4;
  public int JJTWHILESTMT = 5;
  public int JJTCONDITION = 6;
  public int JJTEXPRESSION = 7;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "VarDecl",
    "PrintStmt",
    "IfStmt",
    "WhileStmt",
    "Condition",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=13de0477d339b9fd4919eda62edefb6c (do not edit this line) */
